global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'micro-sender'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['micro-sender:8081']

  - job_name: 'micro-recipient'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['micro-recipient:8082']

  - job_name: 'micro-collector'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['micro-collector:8083']

  - job_name: 'micro-visualizer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['micro-visualizer:8084']
